[package]
name = "calvin_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
dateparser = "0.2.0"
reqwest = "0.11.19"
scraper = "0.17.1"
shuttle-serenity = "0.24.0"
shuttle-runtime = "0.24.0"
serenity = "0.11.5"
shuttle-secrets = "0.24.0"
tokio = "1.26.0"
tracing = "0.1.37"
